#!/bin/sh
export xdistdir=/home/przemio/git/void-packages
cd "$(xdistdir)"
# Rebuild toolchain
./xbps-src pkg binutils && sudo xi -f binutils
./xbps-src pkg gcc && sudo xi -f gcc
./xbps-src pkg kernel-headers && sudo xi -f kernel-headers
./xbps-src pkg glibc-devel && sudo xi -f glibc-devel
./xbps-src pkg glibc-locales && sudo xi -f glibc-locales
./xbps-src pkg glibc && sudo xi -f glibc
./xbps-src pkg libstdc++-devel && sudo xi -f libstdc++-devel
./xbps-src pkg libstdc++-devel && sudo xi -f libstdc++
./xbps-src pkg m4 && sudo xi -f m4
./xbps-src pkg ncurses-libs && sudo xi -f ncurses-libs
./xbps-src pkg ncurses-devel && sudo xi -f ncurses-devel
./xbps-src pkg ncurses && sudo xi -f ncurses
./xbps-src pkg ncurses-libtinfo-libs && sudo xi -f ncurses-libtinfo-libs
./xbps-src pkg ncurses-libtinfo-devel && sudo xi -f ncurses-libtinfo-devel
./xbps-src pkg dash && sudo xi -f dash
./xbps-src pkg bash && sudo xi -f bash
./xbps-src pkg zsh && sudo xi -f zsh
./xbps-src pkg coreutils && sudo xi -f coreutils
./xbps-src pkg diffutils && sudo xi -f diffutils
./xbps-src pkg file && sudo xi -f file
./xbps-src pkg findutils && sudo xi -f findutils
./xbps-src pkg gawk && sudo xi -f gawk
./xbps-src pkg grep && sudo xi -f grep
./xbps-src pkg gzip && sudo xi -f gzip
./xbps-src pkg make && sudo xi -f make
./xbps-src pkg patch && sudo xi -f patch
./xbps-src pkg sed && sudo xi -f sed
./xbps-src pkg tar && sudo xi -f tar
./xbps-src pkg xz && sudo xi -f xz
./xbps-src pkg binutils && sudo xi -f binutils # second round
./xbps-src pkg gcc && sudo xi -f gcc # second round
./xbps-src pkg linux5.10 && sudo xi -f linux5.10
# Rebuild basic system
./xbps-src pkg libstdc++ && sudo xi -f libstdc++
./xbps-src pkg gettext && sudo xi -f gettext
./xbps-src pkg bison && sudo xi -f bison
./xbps-src pkg perl && sudo xi -f perl
./xbps-src pkg python && sudo xi -f python
./xbps-src pkg texinfo && sudo xi -f texinfo
./xbps-src pkg util-linux-libs && sudo xi -f util-linux-libs
./xbps-src pkg util-linux && sudo xi -f util-linux
./xbps-src pkg man-pages && sudo xi -f man-pages
./xbps-src pkg tcl && sudo xi -f tcl
./xbps-src pkg expect && sudo xi -f expect
./xbps-src pkg dejagnu && sudo xi -f dejagnu
./xbps-src pkg glibc && sudo xi -f glibc
./xbps-src pkg zlib && sudo xi -f zlib
./xbps-src pkg bzip2 && sudo xi -f bzip2
./xbps-src pkg xz && sudo xi -f xz
./xbps-src pkg zstd && sudo xi -f zstd
./xbps-src pkg file && sudo xi -f file
./xbps-src pkg readline && sudo xi -f readline
./xbps-src pkg m4 && sudo xi -f m4
./xbps-src pkg flex && sudo xi -f flex
./xbps-src pkg binutils && sudo xi -f binutils
./xbps-src pkg gmp && sudo xi -f gmp
./xbps-src pkg mpfr && sudo xi -f mpfr
./xbps-src pkg mpc && sudo xi -f mpc
./xbps-src pkg attr && sudo xi -f attr
./xbps-src pkg acl && sudo xi -f acl
./xbps-src pkg libcap && sudo xi -f libcap
./xbps-src pkg shadow && sudo xi -f shadow
./xbps-src pkg gcc && sudo xi -f gcc
./xbps-src pkg pkg-config && sudo xi -f pkg-config
./xbps-src pkg ncurses && sudo xi -f ncurses
./xbps-src pkg sed && sudo xi -f sed
./xbps-src pkg psmisc && sudo xi -f psmisc
./xbps-src pkg gettext && sudo xi -f gettext
./xbps-src pkg bison && sudo xi -f bison
./xbps-src pkg grep && sudo xi -f grep
./xbps-src pkg bash && sudo xi -f bash
./xbps-src pkg libtool && sudo xi -f libtool
./xbps-src pkg gdbm && sudo xi -f gdbm
./xbps-src pkg gperf && sudo xi -f gperf
./xbps-src pkg expat && sudo xi -f expat
./xbps-src pkg inetutils && sudo xi -f inetutils
./xbps-src pkg perl && sudo xi -f perl
./xbps-src pkg XML::Parser && sudo xi -f XML::Parser
./xbps-src pkg intltool && sudo xi -f intltool
./xbps-src pkg autoconf && sudo xi -f autoconf
./xbps-src pkg automake && sudo xi -f automake
./xbps-src pkg kmod && sudo xi -f kmod
./xbps-src pkg elfutils && sudo xi -f elfutils
./xbps-src pkg libffi && sudo xi -f libffi
./xbps-src pkg libressl && sudo xi -f libressl
./xbps-src pkg python && sudo xi -f python
./xbps-src pkg ninja && sudo xi -f ninja
./xbps-src pkg meson && sudo xi -f meson
./xbps-src pkg coreutils && sudo xi -f coreutils
./xbps-src pkg check && sudo xi -f check
./xbps-src pkg diffutils && sudo xi -f diffutils
./xbps-src pkg gawk && sudo xi -f gawk
./xbps-src pkg findutils && sudo xi -f findutils
./xbps-src pkg groff && sudo xi -f groff
./xbps-src pkg less && sudo xi -f less
./xbps-src pkg gzip && sudo xi -f gzip
./xbps-src pkg iproute2 && sudo xi -f iproute2
./xbps-src pkg kbd && sudo xi -f kbd
./xbps-src pkg libpipeline && sudo xi -f libpipeline
./xbps-src pkg make && sudo xi -f make
./xbps-src pkg patch && sudo xi -f patch
./xbps-src pkg man-db && sudo xi -f man-db
./xbps-src pkg tar && sudo xi -f tar
./xbps-src pkg texinfo && sudo xi -f texinfo
./xbps-src pkg neovim && sudo xi -f neovim
./xbps-src pkg eudev && sudo xi -f eudev
./xbps-src pkg procps-ng && sudo xi -f procps-ng
./xbps-src pkg util-linux && sudo xi -f util-linux
./xbps-src pkg e2fsprogs && sudo xi -f e2fsprogs
./xbps-src pkg sysklogd && sudo xi -f sysklogd
./xbps-src pkg runit && sudo xi -f runit
