#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
# Source generated colors.

[ -f "$HOME/.cache/wal/colors.sh" ] &&  . "${HOME}/.cache/wal/colors.sh"

#        -lf/nf/cf color
#            Defines the foreground color for low, normal and critical notifications respectively.
# 
#        -lb/nb/cb color
#            Defines the background color for low, normal and critical notifications respectively.
# 
#        -lfr/nfr/cfr color
#            Defines the frame color for low, normal and critical notifications respectively.

 reload_dunst() {
    pkill dunst
    dunst \
	-frame_width 0 \
      -lf  "${color0:-#000000}" \
      -lb  "${color1:-#eeeeee}" \
      -lfr "${color2:-#dddddd}" \
      -nf  "${color0:-#000000}" \
      -nb  "${color4:-#bbbbbb}" \
      -nfr "${color5:-#aaaaaa}" \
      -cf  "${color0:-#000000}" \
      -cb  "${color7:-#888888}" \
      -cfr "${color8:-#777777}" > /dev/null 2>&1 &
}

reload_dunst
