#!/usr/bin/env bash

#  _    _           _         _   _        __ _                      
# | |  | |         | |       | | | |      / _| |                     
# | |__| | ___ _ __| |__  ___| |_| |_   _| |_| |___      ___ __ ___  
# |  __  |/ _ | '__| '_ \/ __| __| | | | |  _| __\ \ /\ / | '_ ` _ \ 
# | |  | |  __| |  | |_) \__ | |_| | |_| | | | |_ \ V  V /| | | | | |
# |_|  |_|\___|_|  |_.__/|___/\__|_|\__,_|_|  \__| \_/\_/ |_| |_| |_|
#                                                                    
#                       A U T O S T A R T                                                                    
#


function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

#### Most 'common' application keybindings are in sxhkdrc.
#### These are interchangeable with other Tiling Window Managers

run sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
#### PyWal
wal -nRa 90 &

#### Autostart Applications ####
setxkbmap -option compose:ralt &  #### Set Compose Key to R-Alt

pkill compton		####  Launch compton
compton -b &

pkill xfce4-screensaver	####  Launch xfce4-screensaver
xfce4-screensaver &

pkill xfce4-notifyd		####  Launch Notifyd
xfce4-notifyd &

pkill volumeicon	####  Launch volumeicon
volumeicon &

pkill conky			####  Launch conky
conky .conkyrc &

pkill xsettingsd	####  Launch xsettingsd
xsettingsd &

pkill nm-applet		####  Launch nm-applet
nm-applet &

pkill dropbox		####  Launch dropbox
dropbox start &

pkill xfce4-power-manager	####  Launch xfce4-power-manager
xfce4-power-manager &

pkill polybar      ####  Launch polybar
~/.config/polybar/launch.sh

lxpolkit & #### Start lxpolkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xset fp+ ~/.local/share/fonts &	####  Launch xset functions
xsetroot -solid '#000000'
xsetroot -cursor_name left_ptr &

######## Start Herbstluftwm (HLWM) ########
hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# set horizontal tiling is standard
hc set_layout horizontal

# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1  # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

#### Keybindings  #####################
# application bindings are in sxhkdrc #
#######################################

# close, reset, quit  
hc keybind $Mod-q quit
hc keybind $Mod-n reload
hc keybind $Mod-r close

# Open Terminal
hc keybind $Mod-Return spawn  kitty

# rofi launcher  
hc keybind F1 spawn		rofi -modi drun,window,run,keys,ssh -show drun -show-icons -sidebar-mode -location 0  -width 320
	
# Show Keybindings
hc keybind $Mod-F1 spawn   ./.local/share/scripts/show_help.sh

# Shared Keybindings
hc keybind $Mod-F2 spawn   ./.local/share/scripts/shared_help.sh

# bspwm Keybindings
hc keybind $Mod-F3


# hlwm Keybindings
hc keybind $Mod-F4


# xfce4 Keybindings
hc keybind $Mod-F5


# Kitty Keybindings
hc keybind $Mod-F6 spawn   ./.local/share/scripts/kitty_help.sh

# rofi Active Tasks 
hc keybind $Mod-F12 spawn  	rofi -modi window -show window -show-icons -sidebar-mode
		
########### Client Movements

# Change client focus...
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# Moving clients to ... on a single Monitor
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# Move clients to ... on dual monitors
# hc keybind $Mod-Shift-h chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# hc keybind $Mod-Shift-Left chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# hc keybind $Mod-Shift-j chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
# hc keybind $Mod-Shift-Down chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
# hc keybind $Mod-Shift-k chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
# hc keybind $Mod-Shift-Up chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
# hc keybind $Mod-Shift-l chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
# hc keybind $Mod-Shift-Right chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

########### Screen Layout Keybindings
hc keybind $Mod-x remove
hc keybind $Mod-m set_layout max 
hc keybind $Mod-v set_layout vertical
hc keybind $Mod-h set_layout horizontal
hc keybind $Mod-Control-v split vertical 0.5
hc keybind $Mod-Control-h split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max grid    \
               , cycle_layout +1

########### Frame Settings

# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# Resize frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

########### Mouse Settings
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

########### Focus Settings
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         use_index +1 --skip-visible
hc keybind $Mod-Shift-Tab   use_index -1 --skip-visible
hc keybind Mod1-Tab         cycle_all +1
hc keybind Mod1-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

########### Reset prior to setting the theme
hc attr theme.reset 1

########### Attribute
hc attr theme.active.color '#A52A2A'
hc attr theme.active.inner_color '#141414'
hc attr theme.active.outer_color '#8B6914'
hc attr theme.background_color '#141414'
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.inner_color black
hc attr theme.inner_width 1
hc attr theme.normal.color '#141414'
hc attr theme.urgent.color orange

########### Set
hc set always_show_frame 1
hc set focus_follows_mouse 1
hc set frame_border_active_color '#8B6914'
hc set frame_border_normal_color '#141414'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#1A1A1A'
hc set frame_border_width 3
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 5
hc set frame_padding 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set tree_style '╾│ ├└╼─┐'
hc set window_gap 5

########## hc Rules
hc unrule -F
hc unlock  # unlock, just to be sure
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on  # give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Steam tag=Steam

########### Tags/ Workspaces

# Names to Display on Menu...
#tag_names=( {1..10} )
#tag_names=("www" "text" "gimp" "meld" "vlc" "mail" "vb" "image" "code" "chat")
#tag_names=("I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")
tag_names=("" "" "" "" "" "" "" "" "" "") 

########### Set Keys for accessing Tags/Workspaces
# Qwerty Keyboard Settings

#tag_keys=( {1..10} 0 )
#tag_keys=( "1" "2" "3" "4" "5" "6" "7" "8" "9" "0" )
tag_keys=("" "" "" "" "" "" "" "" "" "")

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
    fi
done

########### Assign Applications to Tags/Workspaces
hc rule class~'(firefox|Chromium)' tag=2 index=2  focus=on
hc rule class=geany tag=7  index=7 focus=on
hc rule class=VirtualBox Manager tag=8 index=8  focus=on 
hc rule class=Thunar tag=3  index=3 focus=on
hc rule class=Thunderbird tag=8  index=8 focus=on
hc rule class=libreoffice tag=3  index=3 focus=on
hc rule class=calibre tag=0  index=0 pseudotile=on
hc rule class=Gimp tag=4 index=4 pseudotile=on

#####
hc rule class=Oblogout pseudotile=on
hc rule class=Insync pseudotile=on

###########  Dualmonitor setup
#hc detect_monitors
#hc set_monitors 1920x1080+0+0 1920x1080+1920+0
# Find out your monitor name with xrandr or arandr (save and you get this line)
#xrandr --output VGA-1 --primary --mode 1360x768 --pos 0x0 --rotate normal
#xrandr --output DP2 --primary --mode 1920x1080 --rate 60.00 --output LVDS1 --off &
#xrandr --output LVDS1 --mode 1366x768 --output DP3 --mode 1920x1080 --right-of LVDS1
#xrandr --output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off

########### Space/room for Polybar on two monitors
herbstclient pad 0 32 0 0 0
hc pad 1 30
